reactive:
  feign:
    client:
      config:
        default:
          loggerLevel: FULL
        emite-pac:
          loggerLevel: FULL
          url: https://api-stage.emite.dev/v1
          defaultRequestHeaders:
            Authorization:
              -

