reactive:
  feign:
    client:
      config:
        default:
          loggerLevel: FULL
        emite-pac:
          loggerLevel: FULL
          url: https://api-stage.emite.dev/v1
          defaultRequestHeaders:
            Authorization:
              - Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJqdGkiOiJ0TDNlNnlQV3Z4RWJnYVNyS1Vmelc1TlQyNkVaNHhiRjJOOGFFV0g1Iiwic3ViIjoiTmV4dCBUZWNobm9sb2dpZXMgW1NUQUdFXSIsImlzcyI6IkVNSVRFIFtTVEFHRV0iLCJhdWQiOiJCRU5HQUxBIFtTVEFHRV0ifQ.T4hgD3qsYjyWSMwB75ptbrBMQzTrKvVM3X9Cz4W-BQ8

